config/routes.rb
Rails.application.routes.draw do
  get 'flats/search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Verb + Path + Controller + Action
  # Verb </PATH>, to: CONTROLLER#ACTION
  root to: 'pages#home'
  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'login', to: "users#login"
  get 'search', to: 'flats#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def search
    # grab info from the user
    # the user pass it via form
    # and it was displayed in the url

    @location = params[:location]
    @checkin = DateTime.parse(params[:checkin])
    @checkout = DateTime.parse(params[:checkout])
    #location
    #checkin
    #checkout

    # raise
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end

  def home
    @user = 'Miguel'
    @flats = [
      'Montmartre Flat',
      'Paris Mansion',
      'Singapore Palace'
    ]
  end

  def contact
    @members = [ 'thanh', 'dimitri', 'germain', 'damien', 'julien' ]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    render layout: 'special_layout'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flats/search.html.erb
<h1>Search Results!</h1>
<p>Here are all the flats for: <%= @location %></p>


<ul>
  <li>check-in: <%= @checkin.strftime('%A, %b %d') %></li>
  <li>check-out: <%= @checkout.strftime('%A, %b %d') %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Home',root_path, class: 'nav-link active' %>
            </li>
            <li class="nav-item">
              <%= link_to 'About us',about_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Login',login_path, class: 'btn btn-primary' %>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

app/views/pages/home.html.erb
<h1>Welcome to Airbnb <%= @user %></h1>

<%= link_to 'About Us', about_path %>
<%= link_to 'Login now', login_path %>

<form action='search' class='my-3'>
  <label for=''>Location</label>
  <input type='text' name='location'>

  <label for=''>Check in</label>
  <input type='date' name='checkin'>

  <label for=''>Check out</label>
  <input type='date' name='checkout'>

  <input type='submit'>
</form>

<ul>
  <% @flats.each do |flat| %>
   <div class="card" style="width: 18rem;">
    <img src="https://source.unsplash.com/1600x900/?<%= flat %>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= flat %></h5>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
  <% end %>
</ul>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>